terrallende = Expansion(expansion="Cenizas de Terrallende")
scholomance = Expansion(expansion="Academia scholomance")
lunanegra = Expansion(expansion="Locura en la Feria de Luna Negra")
sombras = Expansion(expansion="El auge de las sombras")
uldum = Expansion(expansion="Salvadores de Uldum")
descenso = Expansion(expansion="El Descenso de los dragones")
bosque = Expansion(expansion="El bosque embrujado")
armagebum = Expansion(expansion="El proyecto Armagebum")
rastakhan = Expansion(expansion="La Arena de Rastakhan")
ungoro = Expansion(expansion="Viaje a Un'Goro")
caballeros = Expansion(expansion="Caballeros del Trono Helado")
kobolds = Expansion(expansion="Kobolds & Catacumbas")
susurros = Expansion(expansion="Susurros de los Dioses Antiguos")
karazhan = Expansion(expansion="Una Noche en Karazhan")
gadgetzan = Expansion(expansion="Mafias de Gadgetzan")
naxramas = Expansion(expansion="La maldición de Naxramas")
goblins = Expansion(expansion="Goblins vs Gnomos")
rocanegra = Expansion(expansion="Montaña Roca Negra")
grantorneo = Expansion(expansion="El Gran Torneo")
expedicionarios = Expansion(expansion="Liga de Expedicionarios")