version: '3.4'

services:
  hsdecker:
    build:
      context: .
    image: hsdecker
    container_name: hsdecker
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"
    env_file:
      - ./settings.env
    depends_on:
      - postgres
      
    
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: 
      - ./settings.env



