# Generated by Django 3.1.5 on 2021-01-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20210119_2047'),
        ('decks', '0004_auto_20210125_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='hero_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.heroclass'),
        ),
    ]
