# Generated by Django 3.1.6 on 2021-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_deck_hero_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deck',
            name='size',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
