# Generated by Django 3.1.7 on 2021-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_decks'),
        ('decks', '0008_auto_20210222_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='decks.DeckCard', to='cards.Card'),
        ),
    ]
