# Generated by Django 3.1.4 on 2021-01-11 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(through='decks.DeckCard', to='decks.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.expansion'),
        ),
        migrations.AddField(
            model_name='card',
            name='heroes',
            field=models.ManyToManyField(to='cards.HeroClass'),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(related_name='cards', to='cards.KeyWord'),
        ),
    ]
