# Generated by Django 3.1.4 on 2021-01-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(through='decks.DeckCard', to='decks.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.expansion'),
        ),
        migrations.AddField(
            model_name='card',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.hero'),
        ),
    ]
