# Generated by Django 3.1.4 on 2021-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210104_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='hero',
        ),
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Minion', 'Minion'), ('Spell', 'Spell'), ('Weapon', 'Weapon'), ('Hero', 'Hero')], default='Minion', max_length=6),
        ),
        migrations.AddField(
            model_name='card',
            name='endurance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='heros',
            field=models.ManyToManyField(to='cards.HeroClass'),
        ),
        migrations.AddField(
            model_name='hero',
            name='armor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='health',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(related_name='cards', to='cards.KeyWord'),
        ),
    ]
