# Generated by Django 3.1.4 on 2021-01-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210114_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quality',
            field=models.CharField(choices=[('Free', 'Free'), ('Common', 'Common'), ('Rare', 'Rare'), ('Weapon', 'Epic'), ('Hero', 'Legendary')], default='Common', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='race',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='heroes',
            field=models.ManyToManyField(related_name='cards', to='cards.HeroClass'),
        ),
    ]
