# Generated by Django 3.1.4 on 2021-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('cards', '0005_auto_20210119_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collectible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, null=True, through='decks.DeckCard', to='decks.Deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='cards.KeyWord'),
        ),
    ]
