# Generated by Django 3.1.4 on 2021-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('cards', '0009_auto_20210119_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, through='decks.DeckCard', to='decks.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.KeyWord'),
        ),
        migrations.AlterField(
            model_name='card',
            name='heroes',
            field=models.ManyToManyField(related_name='cards', to='cards.HeroClass'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=models.TextField(max_length=450),
        ),
    ]
