# Generated by Django 3.1.6 on 2021-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20210119_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='standard',
            field=models.BooleanField(default=True),
        ),
    ]
