# Generated by Django 3.1.6 on 2021-02-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='decks',
        ),
    ]
