# Generated by Django 3.1.7 on 2021-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_auto_20210222_1724'),
        ('cards', '0012_remove_card_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, through='decks.DeckCard', to='decks.Deck'),
        ),
    ]
